### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by MTRNord** [PrismarineJS/flying-squid#268]
After trying to connect (with developing Plugin) server logs 

```
C:\Users\Marcel\Documents\development\flying-squid\dist\lib\plugins\login.js:92
                throw _context2.t1;
                ^

TypeError: Cannot read property 'Y' of undefined
    at readSection (C:\Users\Marcel\Documents\development\flying-squid\node_modu
les\prismarine-provider-anvil\dist\chunk.js:62:15)
    at C:\Users\Marcel\Documents\development\flying-squid\node_modules\prismarin
e-provider-anvil\dist\chunk.js:44:12
    at Array.forEach (native)
    at readSections (C:\Users\Marcel\Documents\development\flying-squid\node_mod
ules\prismarine-provider-anvil\dist\chunk.js:43:12)
    at nbtChunkToPrismarineChunk (C:\Users\Marcel\Documents\development\flying-s
quid\node_modules\prismarine-provider-anvil\dist\chunk.js:21:3)
    at Anvil._callee2$ (C:\Users\Marcel\Documents\development\flying-squid\node_
modules\prismarine-provider-anvil\dist\anvil.js:112:51)
    at tryCatch (C:\Users\Marcel\Documents\development\flying-squid\node_modules
\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Users\Marcel\Documents
\development\flying-squid\node_modules\regenerator-runtime\runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\U
sers\Marcel\Documents\development\flying-squid\node_modules\regenerator-runtime\
runtime.js:95:21)
    at step (C:\Users\Marcel\Documents\development\flying-squid\node_modules\bab
el-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Marcel\Documents\development\flying-squid\node_modules\babel-run
time\helpers\asyncToGenerator.js:28:20
    at run (C:\Users\Marcel\Documents\development\flying-squid\node_modules\core
-js\library\modules\es6.promise.js:87:22)
    at C:\Users\Marcel\Documents\development\flying-squid\node_modules\core-js\l
ibrary\modules\es6.promise.js:100:28
    at flush (C:\Users\Marcel\Documents\development\flying-squid\node_modules\co
re-js\library\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

My custom Plugin is:

```
/* -------------------------------------- */
// Author: MTRNord <info@nordgedanken.de>
// Date: 17.08.2016
// Version: 0.0.1
/* -------------------------------------- */
var Moniker = require('moniker');


module.exports.player = function(player, serv) { // Player is a type of entity (entity inject is called first) with added properties and functions
  player.on('command', (command) => {
    if (message == "nickme") {
      var names = Moniker.generator([Moniker.noun]);
      player.username = names.choose();
    }
  });
}
```

**Comment by MTRNord** [comment]
Minecraft Version: 1.8.9
Official Account: Yes
Launcher: Curse Launcher
Git commit of flying-squid: 38b4d4cd2982eedf54979e5f64b6b0b0317b5582

**Comment by mhsjlw** [comment]
Looks like an anvil error. Does the server run fine without the plugin?

**Comment by MTRNord** [comment]
I will test that tomorow (it is 2am in my country)

**Comment by rom1504** [comment]
The problem is your probably closed flying-squid before it had time finishing saving the world. Try to remove the content of the world/ folder and run the server again ;)

**Comment by MTRNord** [comment]
that changed it thanks
