### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by josefredohd** [PrismarineJS/flying-squid#315]
node app.js
/home/cabox/workspace/flying-squid/node_modules/minecraft-protocol/src/transforms/compression.js:3
const [readVarInt, writeVarInt, sizeOfVarInt] = require("protodef").types.varint;
      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:54:16)
    at Module._compile (module.js:375:25)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/home/cabox/workspace/flying-squid/node_modules/minecraft-protocol/src/client.js:5:21)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
cabox@box-codeanywhere:~/workspace/flying-squid$ node app.js
/home/cabox/workspace/flying-squid/node_modules/minecraft-protocol/src/transforms/compression.js:3
const [readVarInt, writeVarInt, sizeOfVarInt] = require("protodef").types.varint;
      ^

**Comment by mhsjlw** [comment]
Update your Node to >=8
