### ISSUE TITLE
Crashes on clientconnect

### ISSUE THREAD

**Issue by theLMGN** [PrismarineJS/flying-squid#316]
```login.js:30
TypeError: Cannot read property 'header' of undefined
    at Object.module.exports.player (c:\Users\theLMGN\Desktop\stuff\node_modules\flying-squid\dist\lib\plugins\header.js:17:59)
    at c:\Users\theLMGN\Desktop\stuff\node_modules\flying-squid\dist\lib\plugins\login.js:67:54
    at Array.forEach (<anonymous>)
    at Object._callee$ (c:\Users\theLMGN\Desktop\stuff\node_modules\flying-squid\dist\lib\plugins\login.js:66:28)
    at tryCatch (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:114:21)
    at tryCatch (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:62:40)
    at maybeInvokeDelegate (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:358:18)
    at Generator.invoke [as _invoke] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:270:32)
    at Generator.prototype.(anonymous function) [as next] (c:\Users\theLMGN\Desktop\stuff\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (c:\Users\theLMGN\Desktop\stuff\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at c:\Users\theLMGN\Desktop\stuff\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (c:\Users\theLMGN\Desktop\stuff\node_modules\core-js\library\modules\_export.js:35:28)
    at Server.<anonymous> (c:\Users\theLMGN\Desktop\stuff\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)```

**Comment by mhsjlw** [comment]
That stack trace is unusable, you forgot the top. Likely running wrong version. Please provide more details

**Comment by theLMGN** [comment]
Alright, updated.

**Comment by mhsjlw** [comment]
What version of Minecraft?

**Comment by theLMGN** [comment]
@mhsjlw 1.12.2

**Comment by theLMGN** [comment]
Same happens with 1.8

**Comment by mhsjlw** [comment]
Something here: https://github.com/PrismarineJS/flying-squid/blob/master/src/lib/plugins/header.js#L5 might need to add a check to see what's up

**Comment by mhsjlw** [comment]
Can you add a console log there and tell me which one is undefined?

**Comment by NoobDoesMC** [comment]
I'm running the most recent version of flying-squid like this:

```js
var mcServer = require("flying-squid");

mcServer.createMCServer({
  "motd": "A Minecraft Server \nRunning flying-squid",
  "port": 25565,
  "max-players": 10,
  "online-mode": true,
  "logging": false,
  "gameMode": 1,
  "generation": {
    "name": "diamond_square",
    "options":{
      "worldHeight": 80
    }
  },
  "kickTimeout": 10000,
  "plugins": {

  },
  "modpe": false,
  "view-distance": 10
});
```

And try to connect with a 1.8.8 minecraft client, and flying-squid crashes:

```
/Users/NoobDoesMC/Downloads/node_modules/flying-squid/dist/lib/plugins/login.js:92
                throw _context2.t1;
                ^

TypeError: Cannot read property 'header' of undefined
    at Object.module.exports.player (/Users/NoobDoesMC/Downloads/node_modules/flying-squid/dist/lib/plugins/header.js:17:59)
    at /Users/NoobDoesMC/Downloads/node_modules/flying-squid/dist/lib/plugins/login.js:67:54
    at Array.forEach (native)
    at Object._callee$ (/Users/NoobDoesMC/Downloads/node_modules/flying-squid/dist/lib/plugins/login.js:66:28)
    at tryCatch (/Users/NoobDoesMC/Downloads/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/theonlygusti/Downloads/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/theonlygusti/Downloads/node_modules/regenerator-runtime/runtime.js:114:21)
    at tryCatch (/Users/NoobDoesMC/Downloads/node_modules/regenerator-runtime/runtime.js:62:40)
    at maybeInvokeDelegate (/Users/NoobDoesMC/Downloads/node_modules/regenerator-runtime/runtime.js:358:18)
    at Generator.invoke [as _invoke] (/Users/NoobDoesMC/Downloads/node_modules/regenerator-runtime/runtime.js:270:32)
    at Generator.prototype.(anonymous function) [as next] (/Users/NoobDoesMC/Downloads/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/Users/NoobDoesMC/Downloads/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/NoobDoesMC/Downloads/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at F (/Users/NoobDoesMC/Downloads/node_modules/core-js/library/modules/_export.js:35:28)
    at Server.<anonymous> (/Users/NoobDoesMC/Downloads/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Server.<anonymous> (/Users/NoobDoesMC/Downloads/node_modules/flying-squid/dist/lib/plugins/login.js:103:18)
```

**Comment by NoobDoesMC** [comment]
Also got it with Wurst 1.8.x and Liteloader 1.8 (with world edit CUI).

**Comment by NoobDoesMC** [comment]
It also didn't work with Minecraft 1.12.2.

Here's all my versions:

```
npm list --depth=1
/Users/NoobDoesMC/Downloads
└─┬ flying-squid@1.0.0
  ├── babel-runtime@6.26.0
  ├── diamond-square@1.0.0
  ├── emit-then@2.0.0
  ├── event-promise@0.0.1
  ├── flatmap@0.0.3
  ├── minecraft-data@2.25.0
  ├── minecraft-protocol@1.5.0
  ├── mkdirp@0.5.1
  ├── moment@2.20.1
  ├── node-dir@0.1.17
  ├── node-promise-es6@0.3.2
  ├── node-uuid@1.4.8
  ├── prismarine-block@1.0.1
  ├── prismarine-chunk@1.7.0
  ├── prismarine-entity@0.2.0
  ├── prismarine-item@1.0.2
  ├── prismarine-provider-anvil@1.1.0
  ├── prismarine-windows@1.1.0
  ├── prismarine-world@1.0.2
  ├── random-seed@0.3.0
  ├── range@0.0.3
  ├── request-promise@3.0.0
  ├── requireindex@1.1.0
  ├── spiralloop@1.0.2
  └── vec3@0.1.3

npm ERR! extraneous: uuid@3.1.0 /Users/NoobDoesMC/Downloads/node_modules/yggdrasil/node_modules/uuid
npm ERR! extraneous: ajv@5.5.2 /Users/NoobDoesMC/Downloads/node_modules/har-validator/node_modules/ajv
npm ERR! extraneous: boom@5.2.0 /Users/NoobDoesMC/Downloads/node_modules/cryptiles/node_modules/boom
npm ERR! extraneous: uuid@3.1.0 /Users/NoobDoesMC/Downloads/node_modules/request/node_modules/uuid
```

**Comment by ethanent** [comment]
@mhsjlw This seems to be a result of a client-triggered uncaught exception. (Those shouldn't be possible to trigger as they allow modified clients to shut down servers.) Actually looking through flying-squid's code I'm noticing a lot of `throw`s. https://github.com/PrismarineJS/flying-squid/search?utf8=%E2%9C%93&q=throw&type=

**Comment by ethanent** [comment]
Further, can confirm that this issue is still occurring on Minecraft versions 1.8.9 (OF) and 1.12.2 (OF).

**Comment by rom1504** [comment]
Flying-squid is promise based so it should throw.

**Comment by ethanent** [comment]
@rom1504 Sure, in many of the cases in which throw is used it could make sense due to promise use / proper handling. In this case, though, (and in others, see #318) the throw isn’t encapsulated by a promise and properly handled.

**Comment by mhsjlw** [comment]
That's fair, yeah. Some things need to reject rather than throw

**Comment by mhsjlw** [comment]
Fixed

**Comment by theLMGN** [comment]
Still having the same issue. :/

**Comment by mhsjlw** [comment]
Are you using master?

**Comment by theLMGN** [comment]
The one on NPM @mhsjlw

**Comment by mhsjlw** [comment]
Use master, the current release is broken. I'll make a patch release later today
