### ISSUE TITLE
Error on Login

### ISSUE THREAD

**Issue by Loonride** [PrismarineJS/flying-squid#324]
I saw similar issues to mine, but could not find a solution. I got this message after trying on 1.8, 1.8.9, 1.9, 1.12.1:

C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\flying-squid\dist\lib\plugins\login.js:92
                throw _context2.t1;
                ^

TypeError: Cannot read property 'header' of undefined
    at Object.module.exports.player (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\flying-squid\dist\lib\plugins\header.js:17:59)
    at C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\flying-squid\dist\lib\plugins\login.js:67:54
    at Array.forEach (<anonymous>)
    at Object._callee$ (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\flying-squid\dist\lib\plugins\login.js:66:28)
    at tryCatch (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\regenerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\regenerator-runtime\runtime.js:114:21)
    at tryCatch (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\regenerator-runtime\runtime.js:62:40)
    at maybeInvokeDelegate (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\regenerator-runtime\runtime.js:358:18)
    at Generator.invoke [as _invoke] (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\regenerator-runtime\runtime.js:270:32)
    at Generator.prototype.(anonymous function) [as next] (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\core-js\library\modules\_export.js:35:28)
    at Server.<anonymous> (C:\Users\student\Documents\Programming\minecraft-server\nodetest1\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12)

Was this problem solved by someone? I am using Node version 8.9.4

**Comment by mhsjlw** [comment]
Are you on master?

**Comment by Loonride** [comment]
yes, I did npm install flying-squid.

**Comment by rom1504** [comment]
That is not master.

Master is when you clone flying-squid using git.

**Comment by mhsjlw** [comment]
@rom1504 we might want to consider a patch release

**Comment by rom1504** [comment]
Can you test if the release is really broken @mhsjlw ?

I find that unlikely.

**Comment by Loonride** [comment]
Release is definitely broken for me. Got master working for myself, here is what I had to do for anyone wondering:

- cloned master (git clone https://github.com/PrismarineJS/flying-squid.git)
- cd flying-squid
- npm update
- tried running node app.js - but files in the src/lib/plugins directory use require("flying-squid") which was not working for me as it is not in my node_modules
- replaced all instances of require("flying-squid") and require('flying-squid') in the src/lib/plugins directory with require("../../../") and everything worked

**Comment by rom1504** [comment]
or just npm install.....

**Comment by mhsjlw** [comment]
Yeah we need a release @rom1504

**Comment by rom1504** [comment]
fixed
