### ISSUE TITLE
Serialization error on Login

### ISSUE THREAD

**Issue by vrogojin** [PrismarineJS/flying-squid#325]
Using nodejs 8.x
OS: Ubuntu 14.04
Trying to login with Minecraft 12.2

February 23rd 2018, 21:44:58 [INFO]: Server listening on port 25565
February 23rd 2018, 21:44:58 seed: 218547331
February 23rd 2018, 21:47:24 [ERR]: Client undefined:undefined : Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
February 23rd 2018, 21:47:35 [ERR]: Client 127.0.0.1:34944 : TypeError: Serialization error for play.toClient.map_chunk.blockEntities : SizeOf error for params.map_chunk.blockEntities : Cannot read property 'length' of undefined
    at ProtoDef.sizeOfArray (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/structures.js:33:41)
    at ProtoDef.sizeOf (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.reduce (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/structures.js:71:25)
    at ProtoDef.sizeOf (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/protodef.js:44:27)
    at ProtoDef.sizeOf (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/conditional.js:36:28)
    at tryCatch (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/utils.js:67:10)
    at ProtoDef.sizeOfSwitch (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/conditional.js:36:10)
    at ProtoDef.sizeOf (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.reduce (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/datatypes/structures.js:71:25)
    at ProtoDef.sizeOf (/mnt/users/home/vrogojin/flying-squid/node_modules/protodef/src/protodef.js:44:27)
February 23rd 2018, 21:47:35 [INFO]: vrogojin disconnected
February 23rd 2018, 21:47:39 [INFO]: vrogojin (127.0.0.1) connected
February 23rd 2018, 21:47:39 [INFO]: position written, player spawning...

Release is broken.
It would be great if it would work. Could you suggest a workaround if it is possible
I was planning to do some development on it.

**Comment by vrogojin** [comment]
Update: It worked for Minecraft 1.8.
But before the connection server reports it is 1.12.2

**Comment by mhsjlw** [comment]
Yeah, that's due to the auto-version-detection features of nmp, the server only supports 1.8 at the moment, 1.12.2 is under-way

**Comment by rom1504** [comment]
There is no autoversion detection server side in nmp.
So I would say that sending 1.12 in the server list is a bug.

**Comment by mhsjlw** [comment]
Confirmed that it does in fact say 1.12 on the connection screen @rom1504

**Comment by rom1504** [comment]
fixed
