### ISSUE TITLE
Cannot "compile" with GULP

### ISSUE THREAD

**Issue by vrogojin** [PrismarineJS/flying-squid#326]
That is what I have when issuing _gulp_ command inside _prismarine-provider-anvil_.
I wonder is this my particular setup issue or a common problem.
I did setup gulp as instructed here: https://github.com/gulpjs/gulp/blob/v3.9.1/docs/getting-started.md

`assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/mnt/users/home/vrogojin/flying-squid/node_modules/prismarine-provider-anvil/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/mnt/users/home/vrogojin/flying-squid/node_modules/prismarine-provider-anvil/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/mnt/users/home/vrogojin/flying-squid/node_modules/prismarine-provider-anvil/gulpfile.js:48:6)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
`

**Comment by mhsjlw** [comment]
Why are you doing this and why is this a flying squid issue?

**Comment by vrogojin** [comment]
> Why are you doing this
I need to modify anvil provider to work with IPFS (https://ipfs.io). I need to store chunks and level data there. Unfortunately, I do not see at the moment the other way, but modifying the prismarine anvil provider for that.

> why is this a flying squid issue?
I apologize for posting into the wrong location. Its _prismarine-provider-anvil_ issue. My mistake.

**Comment by rom1504** [comment]
You don't need to setup gulp, just do npm install.
