### ISSUE TITLE
Error trying to get length of undefined

### ISSUE THREAD

**Issue by JoeHitchens** [PrismarineJS/flying-squid#327]
I get the following error when I try to connect to flying-squid server at localhost from MC 1.12.2
Msg me if you need more details.

j.h.

<img width="1034" alt="screen shot 2018-04-22 at 9 07 11 pm" src="https://user-images.githubusercontent.com/12770681/39106551-46179eee-4671-11e8-9fa0-1c1191eb5967.png">

April 22nd 2018, 20:53:56 [ERR]: Client 127.0.0.1:63853 : TypeError: Serialization error for play.toClient.map_chunk.blockEntities : SizeOf error for params.map_chunk.blockEntities : Cannot read property 'length' of undefined
    at ProtoDef.sizeOfArray (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/structures.js:33:41)
    at ProtoDef.sizeOf (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.reduce (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/structures.js:71:25)
    at ProtoDef.sizeOf (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/protodef.js:44:27)
    at ProtoDef.sizeOf (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/conditional.js:36:28)
    at tryCatch (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/utils.js:67:10)
    at ProtoDef.sizeOfSwitch (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/conditional.js:36:10)
    at ProtoDef.sizeOf (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/protodef.js:145:31)
    at tryDoc (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:30)
    at tryCatch (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/utils.js:63:16)
    at tryDoc (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/utils.js:67:10)
    at typeArgs.reduce (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/structures.js:72:12)
    at Array.reduce (<anonymous>)
    at ProtoDef.sizeOfContainer (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/datatypes/structures.js:71:25)
    at ProtoDef.sizeOf (/Users/joe/work/playground/flying-squid/node_modules/protodef/src/protodef.js:44:27)

**Comment by rom1504** [comment]
Flying squid currently only support 1.8

**Comment by JoeHitchens** [comment]
Will it ever support anything newer?

**Comment by 109C** [comment]
Probably not.

**Comment by rom1504** [comment]
fixed

**Comment by JoeHitchens** [comment]
Wait ... what?  Actually fixed, or just clearing out the issue?

j.h.

**Comment by rom1504** [comment]
ah yeah I might have read this too fast. Anyway, duplicate of https://github.com/PrismarineJS/flying-squid/issues/219 which I'm currently working on
