### ISSUE TITLE
Error on login ( update )

### ISSUE THREAD

**Issue by SecretsMan** [PrismarineJS/flying-squid#332]
I have error on login ...

      setTimeout(() => { throw err }, 0)
                         ^

TypeError: require(...).portal_detector is not a function
    at Object.module.exports.player (/root/serv/src/lib/plugins/portal.js:5:83)
    at Object.keys.filter.forEach.pluginName (/root/serv/src/lib/plugins/login.js:22:52)
    at Array.forEach (<anonymous>)
    at Server.serv._server.on (/root/serv/src/lib/plugins/login.js:22:10)
    at Server.emit (events.js:182:13)
    at loginClient (/root/serv/node_modules/minecraft-protocol/src/server/login.js:134:12)
    at /root/serv/node_modules/minecraft-protocol/src/server/login.js:91:9
    at /root/serv/node_modules/yggdrasil/lib/Server.js:51:7
    at IncomingMessage.<anonymous> (/root/serv/node_modules/phin/lib/phin.compiled.js:1:2111)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1086:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by rom1504** [comment]
Did you git pull ?

Did you made changes ?

**Comment by SecretsMan** [comment]
Yes I delete the line of max-entities ...

The problem is that I want to make a big server from Prismaline but it crash for the least reason ... (too much entity, not the good version etc)

**Comment by rom1504** [comment]
Ok I just tried it. It works fine.

Try again.

**Comment by rom1504** [comment]
I cannot fix any vague problem. If you have a specific problem, describe it with details, and then we can work on fixing it.

**Comment by SecretsMan** [comment]
C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\login.js:28
setTimeout(() => { throw err }, 0)
^

TypeError: require(...).portal_detector is not a function
at Object.module.exports.player (C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\portal.js:5:83)
at Object.keys.filter.forEach.pluginName (C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\login.js:22:52)
at Array.forEach ()
at Server.serv._server.on (C:\Users\Rayan Desfossez\Desktop\serv\src\lib\plugins\login.js:22:10)
at Server.emit (events.js:182:13)
at loginClient (C:\Users\Rayan Desfossez\Desktop\serv\node_modules\minecraft-protocol\src\server\login.js:125:12)
at C:\Users\Rayan Desfossez\Desktop\serv\node_modules\minecraft-protocol\src\server\login.js:86:9
at C:\Users\Rayan Desfossez\Desktop\serv\node_modules\yggdrasil\lib\Server.js:51:7
at IncomingMessage. (C:\Users\Rayan Desfossez\Desktop\serv\node_modules\phin\lib\phin.compiled.js:1:2111)
at IncomingMessage.emit (events.js:187:15)
at endReadableNT (_stream_readable.js:1086:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

I get with error on vanilla setup of flying-squid... on login

**Comment by demipixel** [comment]
What are the exact steps you're taking to download and run flying-squid?

**Comment by SecretsMan** [comment]
- Download
- change name of project in package.json 
- npm i 
- npm i flying-squid
- node app.js
- Minecrafft Client : Login...
- Error

**Comment by demipixel** [comment]
That's because the npm version doesn't have `portal_detector` and isn't updated. Instead of `npm i flying-squid` you should run `npm i https://github.com/PrismarineJS/flying-squid` (or a link to the specific commit if you're not using the latest master commit).

**Comment by SecretsMan** [comment]
Okay
 thanks !!
