### ISSUE TITLE
Error with entities

### ISSUE THREAD

**Issue by SecretsMan** [PrismarineJS/flying-squid#339]
I go on my server and break a block and : 

flying-squid\src\lib\plugins\entities.js:28
      .catch((err) => setTimeout(() => { throw err }, 0))
                                         ^

TypeError: Cannot read property 'type' of null
    at Entity.player.collect (C:\Users\Rayan Desfossez\Desktop\flying-squid\src\lib\plugins\inventory.js:185:16)
    at Promise.all.Object.keys.map (C:\Users\Rayan Desfossez\Desktop\flying-squid\src\lib\plugins\entities.js:19:24)
    at Array.map (<anonymous>)
    at MCServer.<anonymous> (C:\Users\Rayan Desfossez\Desktop\flying-squid\src\lib\plugins\entities.js:7:34)
    at MCServer.emit (events.js:187:15)
    at Timeout.serv.tickInterval.setInterval [as _onTimeout] (C:\Users\Rayan Desfossez\Desktop\flying-squid\src\lib\plugins\tick.js:13:12)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)

**Comment by demipixel** [comment]
This is what happens when people use `item === undefined` as oppose to `item`... ;)

**Comment by SecretsMan** [comment]
What should be done?

**Comment by rom1504** [comment]
I'm not fixing anything until https://github.com/PrismarineJS/flying-squid/pull/333 is merged.

**Comment by rom1504** [comment]
and @demipixel no, relying on js conversion stuff is a bad idea. You should use undefined or null with precision, not just any null-looklike thing

**Comment by SecretsMan** [comment]
But how should I go about solving this problem?
When will you send the update?

**Comment by rom1504** [comment]
If you want the fix now, you can read the code and fix it yourself.
If you want to "do a big server" with flying squid, you are going to have
to implement new features anyway, so you might as well start understanding
its code now.

So what you can do is go at the line your error message say, log some
variables around it and figure out what's wrong in the current code. Then
you can fix it, make sure it doesn't happen anymore. And push the fix.

Or you can wait for me to fix it later this week, but then you won't have
learned much.

Your choice.

Regardless I don't have that much time so don't except a quick fix from me.
Maybe later this week.

**Comment by rom1504** [comment]
ok tried, breaking a block works.
Re-open if it doesn't work with the new version
