### ISSUE TITLE
TypeError: Cannot read property header of undefined

### ISSUE THREAD

**Issue by SuperAuguste** [PrismarineJS/flying-squid#349]

**Comment by demipixel** [comment]
Could you provide the full error?

**Comment by SuperAuguste** [comment]
mclink server listening on port 25565
C:\Users\augus\Desktop\Programming\mclink\node_modules\flying-squid\src\lib\plugins\login.js:28
      setTimeout(() => { throw err }, 0)
                         ^

TypeError: Cannot read property 'header' of undefined
    at Object.module.exports.player (C:\Users\augus\Desktop\Programming\mclink\node_modules\flying-squid\src\lib\plugins\header.js:8:59)
    at Object.keys.filter.forEach.pluginName (C:\Users\augus\Desktop\Programming\mclink\node_modules\flying-squid\src\lib\plugins\login.js:22:52)
    at Array.forEach (<anonymous>)
    at Server.serv._server.on (C:\Users\augus\Desktop\Programming\mclink\node_modules\flying-squid\src\lib\plugins\login.js:22:10)
    at Server.emit (events.js:160:13)
    at loginClient (C:\Users\augus\Desktop\Programming\mclink\node_modules\minecraft-protocol\src\server\login.js:125:12)
    at C:\Users\augus\Desktop\Programming\mclink\node_modules\minecraft-protocol\src\server\login.js:86:9
    at C:\Users\augus\Desktop\Programming\mclink\node_modules\yggdrasil\lib\Server.js:51:7
    at IncomingMessage.<anonymous> (C:\Users\augus\Desktop\Programming\mclink\node_modules\phin\lib\phin.compiled.js:1:2111)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by demipixel** [comment]
It's having an issue reading your settings. Make sure you follow this template:

https://github.com/PrismarineJS/flying-squid/blob/master/config/default-settings.json

You may be having issues if you're using a settings config from a previous flying-squid version.

**Comment by SuperAuguste** [comment]
Thank you so much @demipixel, you saved my day! The problem was indeed the configuration. I followed the configuration on the README and it seems that it was indeed from a previous version.
