### ISSUE TITLE
Chunk size is 55 but only 4 was read - error (Minecraft version: 1.13)

### ISSUE THREAD

**Issue by umutozdemir97** [PrismarineJS/flying-squid#355]
This error is not present in Minecraft 1.12.2. But there are other errors in that version. 

After I install the required packages with `npm install` and start `app.js`, I get this error. Not immediately. When I try to connect to localhost, this error is added to console:

```
Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
August 5th 2018, 00:06:37 [ERR]: Client undefined:undefined : Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
```

Minecraft version: 1.13 
Java executable for Minecraft:  jre1.8.0_181

```
PS C:\Users\HP> node -v
v8.1.4
```

Full error log (repetitive): 

```
PS C:\Users\HP\Desktop\mcs\flying-squid> node app.js
August 5th 2018, 00:05:33 [INFO]: Server listening on port 25565
August 5th 2018, 00:05:33 seed: 627589545
Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
August 5th 2018, 00:05:46 [ERR]: Client undefined:undefined : Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
August 5th 2018, 00:05:47 [ERR]: Client undefined:undefined : Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
August 5th 2018, 00:05:47 [ERR]: Client undefined:undefined : Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
August 5th 2018, 00:05:47 [ERR]: Client undefined:undefined : Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
Chunk size is 55 but only 3 was read ; partial packet : {"name":"legacy_server_list_ping","params":{"payload":1}}; buffer :fe0101fa000b004d0043007c00500069006e00670048006f0073007400197f0009006c006f00630061006c0068006f00730074000063dd
August 5th 2018, 00:06:37 [ERR]: Client undefined:undefined : Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:610:25)
```

**Comment by rom1504** [comment]
minecraft 1.13 is not supported yet. see #341

**Comment by blubbll** [comment]
getting the same with the current release (1.2.0) at minecraft 1.12
