### ISSUE TITLE
Spawning mobs crashes server?? (realised they're not added yet)

### ISSUE THREAD

**Issue by 160Productions** [PrismarineJS/flying-squid#356]
The one major downside that I've noticed so far is that any attempt at spawning mobs, for some reason, crashes the server with the error provided below. Any ideas? I haven't seen anyone else with this problem so it may be something I've missed.

> **TypeError: Cannot read property 'name' of undefined
    at MCServer.serv.spawnMob (...\bot\node_modules\flying-squid\src\lib\plugins\spawn.js:54:31)
    at Client.player._client.on (...\bot\node_modules\flying-squid\src\lib\plugins\useItem.js:14:162)
    at emitTwo (events.js:131:20)
    at Client.emit (events.js:214:7)
    at FullPacketParser.deserializer.on (...\bot\node_modules\minecraft-protocol\src\client.js:82:12)
    at emitOne (events.js:116:13)
    at FullPacketParser.emit (events.js:211:7)
    at addChunk (...\bot\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (...\bot\node_modules\readable-stream\lib\_stream_readable.js:278:11)
    at FullPacketParser.Readable.push (...\bot\node_modules\readable-stream\lib\_stream_readable.js:245:10)
    at FullPacketParser.Transform.push (...\bot\node_modules\readable-stream\lib\_stream_transform.js:148:32)
    at FullPacketParser._transform (C:\Users\Callum\Desktop\bot\node_modules\protodef\src\serializer.js:85:10)
    at FullPacketParser.Transform._read (...\bot\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at FullPacketParser.Transform._write (...\bot\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\Callum\Desktop\bot\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (...\bot\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at FullPacketParser.Writable.write (....\bot\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Decompressor.ondata (...\bot\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at emitOne (events.js:116:13)
    at Decompressor.emit (events.js:211:7)
    at addChunk (...\bot\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (...\bot\node_modules\readable-stream\lib\_stream_readable.js:278:11)**

**Comment by rom1504** [comment]
yes flying squid has mobs, how did you produce that error ?
