### ISSUE TITLE
Cannot find plugin

### ISSUE THREAD

**Issue by 4xk** [PrismarineJS/flying-squid#366]
Im trying to register a plugin, I've looked [at this](https://github.com/PrismarineJS/flying-squid/blob/master/docs/CONTRIBUTE.md#creating-external-plugins)

Im still getting a "Cannot find plugin plugin name"
```F:\coding\js\mc\node_modules\flying-squid\src\lib\plugins\external.js:29
        throw new Error('Cannot find plugin "' + p + '"')
        ^

Error: Cannot find plugin "plugin_name"
    at Object.keys.forEach (F:\coding\js\mc\node_modules\flying-squid\src\lib\plugins\external.js:29:15)
    at Array.forEach (<anonymous>)
    at Object.module.exports.server (F:\coding\js\mc\node_modules\flying-squid\src\lib\plugins\external.js:21:33)
    at Object.keys.filter.forEach.pluginName (F:\coding\js\mc\node_modules\flying-squid\src\index.js:48:50)
    at Array.forEach (<anonymous>)
    at MCServer.connect (F:\coding\js\mc\node_modules\flying-squid\src\index.js:48:8)
    at Object.createMCServer (F:\coding\js\mc\node_modules\flying-squid\src\index.js:27:12)
    at Object.<anonymous> (F:\coding\js\mc\src\server.js:4:10)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\coding\js\mc\index.js:1:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
[nodemon] app crashed - waiting for file changes before starting...```

My project structure is like so
/
    (index.js)[https://hastebin.com/fiwejelaka.js] - Requires src/server.js to start server
    package.json
    src/
       (server.js)[https://hastebin.com/iminaderic.js]
          /plugins
                [plugin_name.js](https://hastebin.com/lufowetisu.coffeescript)


I've also tried using src/lib/plugins, and just lib/plugins, and /plugins.

**Comment by 4xk** [comment]
Woop, i wish i could edit to fix the code block. Heres it with working links
My project structure is like so
/
    (index.js)[https://hastebin.com/fiwejelaka.js] - Requires src/server.js to start server
    package.json
    src/
       (server.js)[https://hastebin.com/iminaderic.js]
          /plugins
                [plugin_name.js](https://hastebin.com/lufowetisu.coffeescript)

**Comment by demipixel** [comment]
Create a folder called `plugin_name` inside the plugins folder and rename your js file to `index.js` and put it in your new folder.

**Comment by demipixel** [comment]
Also I would check out the README.md in the plugins folder for more information. The one you linked is for internal plugins.

**Comment by 4xk** [comment]
Moving the js file to plugins/plugin_name did not work.

[Heres what my package structure looks like ](https://sharex.cf/0mt.png)

**Comment by demipixel** [comment]
Hmm, that's odd. It seems like your project structure is:

- src
  - lib
    - plugins
      - your_plugin_here

But from what I see on the repo it should be:

-src
  - lib
    - a bunch of important stuff in here
  - plugins
    - your_plugin_here

unless I'm misunderstanding what you're trying to do.

**Comment by 4xk** [comment]
I've changed my project structure to what you said, and its still not finding the plugin.

Would you like for me to put my full code in a repo?

**Comment by demipixel** [comment]
I'm not saying you should change it to that structure, moreso that it should have been in that structure when you cloned it... but yeah, you can if you'd like.

**Comment by 4xk** [comment]
I didnt clone it from anywere, i used examples. [This is the entire project](https://github.com/4xk/flying-squid-plugin-issue)

**Comment by demipixel** [comment]
Ahhh I see. I believe the only way to run plugins is to go to flying squid and click "Clone or Download" -> "Download as zip". Then put your plugin folder in `/src/plugins/`. I don't remember but I don't think there's a way to use flying-squid as a library and use your own custom plugins (at least as of yet).

**Comment by 4xk** [comment]
Ohhhhh okay. im going to try this in a fews minutes, will report back.

**Comment by 4xk** [comment]
Thank you!
