### ISSUE TITLE
Item throw error/bug

### ISSUE THREAD

**Issue by GameofTurkey** [PrismarineJS/flying-squid#369]
Error:
```
/home/pi/Desktop/NodeJS_MC/node_modules/minecraft-protocol/src/transforms/framing.js:66
          } else { throw e }
                   ^

TypeError: Cannot read property 'type' of undefined
```
I tried throw item while inventory was open. I mean I moved cursor to item then pressed q. After that server crashed.

**Comment by rom1504** [comment]
Full error, full code

**Comment by GameofTurkey** [comment]
Full log
```
[Essentials] Plugin enabled
September 15th 2019, 19:58:51 [PLUGINS] Loaded "flying-squid-essentials"
September 15th 2019, 19:58:51 [INFO]: Server listening on port 25565
September 15th 2019, 19:58:51 seed: 1320044072
September 15th 2019, 19:59:19 [INFO]: RisksY (127.0.0.1) connected
September 15th 2019, 19:59:19 [INFO]: position written, player spawning...
/home/risksy/Desktop/NodeJS_MC/node_modules/minecraft-protocol/src/transforms/framing.js:66
          } else { throw e }
                   ^

TypeError: Cannot read property 'type' of undefined
    at Client.<anonymous> (/home/risksy/Desktop/NodeJS_MC/src/lib/plugins/inventory.js:75:32)
    at Client.emit (events.js:189:13)
    at FullPacketParser.deserializer.on (/home/risksy/Desktop/NodeJS_MC/node_modules/minecraft-protocol/src/client.js:82:12)
    at FullPacketParser.emit (events.js:189:13)
    at addChunk (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_readable.js:297:12)
    at readableAddChunk (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_readable.js:279:11)
    at FullPacketParser.Readable.push (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_readable.js:240:10)
    at FullPacketParser.Transform.push (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at FullPacketParser._transform (/home/risksy/Desktop/NodeJS_MC/node_modules/protodef/src/serializer.js:81:10)
    at FullPacketParser.Transform._read (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at FullPacketParser.Transform._write (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_writable.js:405:139)
    at writeOrBuffer (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_writable.js:394:5)
    at FullPacketParser.Writable.write (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_writable.js:303:11)
    at Decompressor.ondata (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_readable.js:662:20)
    at Decompressor.emit (events.js:189:13)
    at addChunk (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_readable.js:297:12)
    at readableAddChunk (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_readable.js:279:11)
    at Decompressor.Readable.push (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_readable.js:240:10)
    at Decompressor.Transform.push (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Decompressor._transform (/home/risksy/Desktop/NodeJS_MC/node_modules/minecraft-protocol/src/transforms/compression.js:52:12)
    at Decompressor.Transform._read (/home/risksy/Desktop/NodeJS_MC/node_modules/readable-stream/lib/_stream_transform.js:177:10)
```
I used latest flying-squid didn't change any code. To make crash server, throw item on survival after pick up block with breaking it.

**Comment by GameofTurkey** [comment]
I tried again in my computer. So username is risksy this time.

**Comment by demipixel** [comment]
Line 75

https://github.com/PrismarineJS/flying-squid/blob/1b519708bc661613f5aec3fa048138f03eb93a2b/src/lib/plugins/inventory.js#L68-L79
