### ISSUE TITLE
Unable to join after leaving again (Same session, server instance)

### ISSUE THREAD

**Issue by Technisha** [PrismarineJS/flying-squid#464]
Heya! I'm getting an error when trying to rejoin my server, here's the error:
```January 16th 2021, 20:15:17 [ERR]: Client ::1:45760 : Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:456:14)
    at Cipheriv.ondata (_stream_readable.js:719:22)
    at Cipheriv.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Cipheriv.Readable.push (_stream_readable.js:223:10)
    at Cipheriv.Transform.push (_stream_transform.js:166:32)
    at Cipheriv._transform (internal/crypto/cipher.js:135:8)
    at Cipheriv.Transform._read (_stream_transform.js:205:10)
    at Cipheriv.Transform._write (_stream_transform.js:193:12)
    at writeOrBuffer (_stream_writable.js:352:12)
    at Cipheriv.Writable.write (_stream_writable.js:303:10)
    at Framer.ondata (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Framer.emit (events.js:315:20)
    at addChunk (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Framer.Readable.push (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Framer.Transform.push (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Framer._transform (/home/raees/repos/flying-squid-software-test/node_modules/minecraft-protocol/src/transforms/framing.js:20:10)
    at Framer.Transform._read (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Framer.Transform._write (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Framer.Writable.write (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Compressor.ondata (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Compressor.emit (events.js:315:20)
    at addChunk (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Compressor.Readable.push (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Compressor.Transform.push (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Compressor._transform (/home/raees/repos/flying-squid-software-test/node_modules/minecraft-protocol/src/transforms/compression.js:35:12)
    at Compressor.Transform._read (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Compressor.Transform._write (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Compressor.Writable.write (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Serializer.ondata (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:681:20)
    at Serializer.emit (events.js:315:20)
    at addChunk (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:298:12)
    at readableAddChunk (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:280:11)
    at Serializer.Readable.push (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_readable.js:241:10)
    at Serializer.Transform.push (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:139:32)
    at Serializer._transform (/home/raees/repos/flying-squid-software-test/node_modules/protodef/src/serializer.js:22:10)
    at Serializer.Transform._read (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:177:10)
    at Serializer.Transform._write (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_transform.js:164:83)
    at doWrite (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Serializer.Writable.write (/home/raees/repos/flying-squid-software-test/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Client.write (/home/raees/repos/flying-squid-software-test/node_modules/minecraft-protocol/src/client.js:221:21)
    at Entity.player.chat (/home/raees/repos/flying-squid-software-test/node_modules/flying-squid/src/lib/plugins/chat.js:148:20)
    at /home/raees/repos/flying-squid-software-test/node_modules/flying-squid/src/lib/plugins/chat.js:8:27
    at Array.forEach (<anonymous>:null:null)
    at MCServer.serv.broadcast (/home/raees/repos/flying-squid-software-test/node_modules/flying-squid/src/lib/plugins/chat.js:7:56)
    at Client.<anonymous> (/home/raees/repos/flying-squid-software-test/node_modules/flying-squid/src/lib/plugins/logout.js:22:12)
    at Client.emit (events.js:327:22)
    at Socket.endSocket (/home/raees/repos/flying-squid-software-test/node_modules/minecraft-protocol/src/client.js:145:12)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)```

**Comment by Technisha** [comment]
Update: I'm unable to rejoin the server after restarting it either.

**Comment by Technisha** [comment]
Update: Fixed after deleting the world folder
And i also haven't been able to reproduce the bug
