### ISSUE TITLE
When i want to join the server

### ISSUE THREAD

**Issue by TapsHTS** [PrismarineJS/flying-squid#468]
![image](https://user-images.githubusercontent.com/61658427/105974799-8c46ba00-608e-11eb-8ee9-a976b355258a.png)

**Comment by TapsHTS** [comment]
And in the console: 
```js
[ERR]: Client ::ffff:127.0.0.1:51199 : TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be of type string or an instance of Buffer or ArrayBuffer. Received undefined
    at Function.byteLength (buffer.js:728:11)
    at Object.shortString (eval at compile (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:245:12), <anonymous>:45:25)
    at nbt (eval at compile (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:245:12), <anonymous>:110:32)
    at CompiledProtodef.sizeOf (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:77:14)
    at Object.sizeOfNbt [as nbt] (D:\Users\legot\Visual\flying-squid\node_modules\minecraft-protocol\src\datatypes\minecraft.js:41:20)
    at Object.packet_login (eval at compile (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:245:12), <anonymous>:1078:24)
    at eval (eval at compile (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:245:12), <anonymous>:2292:50)
    at packet (eval at compile (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:245:12), <anonymous>:2346:9)
    at CompiledProtodef.sizeOf (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:77:14)
    at e.message (D:\Users\legot\Visual\flying-squid\node_modules\protodef\src\compiler.js:84:40)
January 27th 2021, 11:01:09 [ERR]: Client ::ffff:127.0.0.1:51199 : Error: read ECONNRESET
```

Server version: 1.16.4

**Comment by TapsHTS** [comment]
Ok. 1.16.4 it's not supported
