### ISSUE TITLE
TypeError: Cannot read property 'biomes' of undefined

### ISSUE THREAD

**Issue by TapsHTS** [PrismarineJS/flying-squid#584]
I have this error:

```
TypeError: Cannot read property 'biomes' of undefined
    at prismarineChunkToNbt (/home/container/node_modules/prismarine-provider-anvil/src/1.14/chunk.js:25:38)
    at Anvil.save (/home/container/node_modules/prismarine-provider-anvil/src/anvil.js:44:19)
    at World.saveNow (/home/container/node_modules/prismarine-world/src/world.js:139:30)
    at Timeout._onTimeout (/home/container/node_modules/prismarine-world/src/world.js:147:18)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

**Comment by darksunlight** [comment]
Duplicate of #566

**Comment by Pandapip1** [comment]
@rom1504 this is a duplicate and should be closed.
