### ISSUE TITLE
error when i start the server

### ISSUE THREAD

**Issue by hi12167pies** [PrismarineJS/flying-squid#628]
It says to report it here, I tried to look through some code but I'm not sure

```
July 18th 2023, 18:53:28 [INFO]: Server listening on port 25565
TypeError: invalid options argument
    at optsArg (C:\Users\User\Documents\Code\mc\flying-squid\node_modules\mkdirp\dist\cjs\src\opts-arg.js:19:15)
    at exports.mkdirp.Object.assign.mkdirpSync (C:\Users\User\Documents\Code\mc\flying-squid\node_modules\mkdirp\dist\cjs\src\index.js:30:48)
    at serv.createLog (C:\Users\User\Documents\Code\mc\flying-squid\src\lib\plugins\log.js:67:5)
    at MCServer.connect (C:\Users\User\Documents\Code\mc\flying-squid\src\index.js:58:40)
    at Object.createMCServer (C:\Users\User\Documents\Code\mc\flying-squid\src\index.js:35:12)
    at Object.<anonymous> (C:\Users\User\Documents\Code\mc\flying-squid\app.js:32:27)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
July 18th 2023, 18:53:28 [INFO]: World seed: 20044673
July 18th 2023, 18:53:36 [ERROR]: -------------------------------
July 18th 2023, 18:53:36 [ERROR]: Please report this flying-squid! This is bug (mabye)
July 18th 2023, 18:53:36 [ERROR]: Something went wrong!
July 18th 2023, 18:53:36 [ERROR]: Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at Function.from (node:buffer:339:9)
    at readBlocks (C:\Users\User\Documents\Code\mc\flying-squid\node_modules\prismarine-provider-anvil\src\1.8\chunk.js:83:21)
    at readSection (C:\Users\User\Documents\Code\mc\flying-squid\node_modules\prismarine-provider-anvil\src\1.8\chunk.js:56:5)
    at C:\Users\User\Documents\Code\mc\flying-squid\node_modules\prismarine-provider-anvil\src\1.8\chunk.js:39:33
    at Array.forEach (<anonymous>)
    at readSections (C:\Users\User\Documents\Code\mc\flying-squid\node_modules\prismarine-provider-anvil\src\1.8\chunk.js:39:14)
    at nbtChunkToPrismarineChunk (C:\Users\User\Documents\Code\mc\flying-squid\node_modules\prismarine-provider-anvil\src\1.8\chunk.js:9:5)
    at Anvil.load (C:\Users\User\Documents\Code\mc\flying-squid\node_modules\prismarine-provider-anvil\src\anvil.js:34:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
July 18th 2023, 18:53:36 [ERROR]: Report this error here: https://github.com/PrismarineJS/flying-squid/issues
July 18th 2023, 18:53:36 [ERROR]: -------------------------------
>
```

**Comment by hi12167pies** [comment]
* Also I joined then the second error shows and server stops.
