### ISSUE TITLE
Compatibility with original 1.16.1 saves (worlds)?

### ISSUE THREAD

**Issue by zardoy** [PrismarineJS/flying-squid#632]
I've been trying to achieve something like was asked in https://github.com/PrismarineJS/flying-squid/issues/477
So when I try to use world generated from java 1.16.1 server I get the following:

```
August 25th 2023, 04:28:20 [ERROR]: Error: TypeError: Cannot read properties of undefined (reading 'id')
    at ChunkColumn.getBlockType (C:\Users\AudioMaster\Desktop\repos\flying-squid\node_modules\prismarine-chunk\src\pc\1.16\ChunkColumn.js:101:51)
    at World.getBlockType (C:\Users\AudioMaster\Desktop\repos\flying-squid\node_modules\prismarine-world\src\world.js:238:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async findSpawnZone (C:\Users\AudioMaster\Desktop\repos\flying-squid\src\lib\plugins\settings.js:19:13)
    at async player.findSpawnPoint (C:\Users\AudioMaster\Desktop\repos\flying-squid\src\lib\plugins\settings.js:39:25)
    at async addPlayer (C:\Users\AudioMaster\Desktop\repos\flying-squid\src\lib\plugins\login.js:57:5)
    at async player.login (C:\Users\AudioMaster\Desktop\repos\flying-squid\src\lib\plugins\login.js:222:5)
    at async Server.<anonymous> (C:\Users\AudioMaster\Desktop\repos\flying-squid\src\lib\plugins\login.js:29:7)
```

However I originally noticed it when after following actions:
- generate world with flying-squid
- use this world with java server (world is loadable)
- use the same world in flying-squid again (not loadable anymore)

I'm not sure, probably it is an issue with prismarine chunk, but I believe it was tested with original worlds, right?

**Comment by rom1504** [comment]
Flying-squid does not support recent version, do you want to help updating it?

**Comment by zardoy** [comment]
> Flying-squid does not support recent version, do you want to help updating it?

Not sure what you mean, but why not

**Comment by Pandapip1** [comment]
@rom1504 this issue should be closed probably.
