### ISSUE TITLE
Possible path to follow when fixing chunks.

### ISSUE THREAD

**Issue by FabioSmuu** [PrismarineJS/flying-squid#658]
I made the chunk changes from **1.16.5** to **1.17.1** and then I went straight to debugging.

In my analysis I noticed that when reentering the world, the **sectionMask** sometimes doesn't have **toLongArray**.

I did a StackTracer until I found the key and it was indeed in the rendering of the chunk.

The problem occurs when the player leaves and reenters the server (this will be worse if you force the server to shut down.)

So, yes, the problem is related to saving the world and in the chunk.

See my logs:
```log
[OK][Smuu Log] typof sectionMask object
[OK][Smuu Log] typof skyLightMask object
[OK][Smuu Log] typof blockLightMask object
[Smuu Log] TypeError: this.sectionMask.toLongArray is not a function
    at ChunkColumn.getMask (ChunkColumn.js:244:31)
    at world.js:190:33
    at Entity.behavior (behavior.js:24:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async player.login (login.js:223:9)
    at async Server.<anonymous> (login.js:29:7) TypeError: this.sectionMask.toLongArray is not a function
    at ChunkColumn.getMask (/home/fabio/Documentos/nodejs/minecraft-flying-squid/flying-squid/node_modules/prismarine-chunk/src/pc/1.17/ChunkColumn.js:244:31)
    at /home/fabio/Documentos/nodejs/minecraft-flying-squid/flying-squid/src/lib/plugins/world.js:190:33
    at Entity.behavior (/home/fabio/Documentos/nodejs/minecraft-flying-squid/flying-squid/src/lib/behavior.js:24:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async player.login (/home/fabio/Documentos/nodejs/minecraft-flying-squid/flying-squid/src/lib/plugins/login.js:223:9)
    at async Server.<anonymous> (/home/fabio/Documentos/nodejs/minecraft-flying-squid/flying-squid/src/lib/plugins/login.js:29:7)
[Smuu Log] typof sectionMask number
[Smuu Log] typof skyLightMask number
[Smuu Log] typof blockLightMask object
```

What I did was just a try/catch after the StackTracer.

**Comment by rom1504** [comment]
Thanks fixed now
